### ISSUE TITLE
Low denial of service vulnerability reported for mem

### ISSUE THREAD

**Issue by iapazmino** [telus/semantic-release-config#21]
*Report:*
 Low           │ Denial of Service                                            │
│ Package       │ mem                                                          │
│ Patched in    │ >=4.0.0                                                      │
│ Dependency of │ semantic-release                                             │
│ Path          │ semantic-release > @semantic-release/npm > npm > libnpx >    │
│               │ yargs > os-locale > mem                                      │
│ More info     │ https://npmjs.com/advisories/1084                            │

│ Low           │ Denial of Service                                            │
│ Package       │ mem                                                          │
│ Patched in    │ >=4.0.0                                                      │
│ Dependency of │ @telus/semantic-release-config [dev]                         │
│ Path          │ @telus/semantic-release-config > @semantic-release/npm > npm │
│               │ > libnpx > yargs > os-locale > mem                           │
│ More info     │ https://npmjs.com/advisories/1084                            │

*Installed version of mem is 1.1.0*

**Comment by antsav** [comment]
+1

**Comment by rebekahshaw92** [comment]
I am having the same problem, anyone able to fix it?

**Comment by schmidt-andre** [comment]
I do the following
1. remove node_modules
# rm-r node_modules
2. insert resultions in package.json
  "resolutions": {
    "os-locale": "^4.0.0"
  }
3. change resolution with npx npm-force-resolutions
# npx npm-force-resolutions
4. npm install
# npm install

Good luck
